name = "mdm-docs-superinfo"
compatibility_date = "2026-01-20"

# 必須包含 nodejs_compat 才能跑 Next.js 的伺服器邏輯
compatibility_flags = ["nodejs_compat"]

# 這是 Pages 的配置方式
pages_build_output_dir = ".open-next"

[observability]
enabled = true